/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCompaniesRouteRouteImport } from './routes/_app/companies/route'
import { Route as AppDeliveriesRouteRouteImport } from './routes/_app/deliveries/route'
import { Route as AppMaterialsRouteRouteImport } from './routes/_app/materials/route'
import { Route as AppPurchasesRouteRouteImport } from './routes/_app/purchases/route'
import { Route as AppSalesOrdersRouteRouteImport } from './routes/_app/sales-orders/route'
import { Route as AppCompaniesIndexRouteImport } from './routes/_app/companies/index'
import { Route as AppCompaniesCompanyIdRouteImport } from './routes/_app/companies/$companyId'
import { Route as AppCompanyReportIndexRouteImport } from './routes/_app/company-report/index'
import { Route as AppDeliveriesIndexRouteImport } from './routes/_app/deliveries/index'
import { Route as AppMaterialsIndexRouteImport } from './routes/_app/materials/index'
import { Route as AppMaterialsMaterialIdRouteImport } from './routes/_app/materials/$materialId'
import { Route as AppPurchasesIndexRouteImport } from './routes/_app/purchases/index'
import { Route as AppRateAnalysisIndexRouteImport } from './routes/_app/rate-analysis/index'
import { Route as AppSalesOrdersIndexRouteImport } from './routes/_app/sales-orders/index'
import { Route as AppSalesOrdersOrderIdRouteImport } from './routes/_app/sales-orders/$orderId'
import { Route as AppSupplierStockIndexRouteImport } from './routes/_app/supplier-stock/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRouteRoute = AppCompaniesRouteRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesRouteRoute = AppDeliveriesRouteRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsRouteRoute = AppMaterialsRouteRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRouteRoute = AppPurchasesRouteRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersRouteRoute = AppSalesOrdersRouteRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCompaniesRouteRoute,
} as any)
const AppCompaniesCompanyIdRoute = AppCompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => AppCompaniesRouteRoute,
} as any)
const AppCompanyReportIndexRoute = AppCompanyReportIndexRouteImport.update({
  id: '/company-report/',
  path: '/company-report/',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesIndexRoute = AppDeliveriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDeliveriesRouteRoute,
} as any)
const AppMaterialsIndexRoute = AppMaterialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMaterialsRouteRoute,
} as any)
const AppMaterialsMaterialIdRoute = AppMaterialsMaterialIdRouteImport.update({
  id: '/$materialId',
  path: '/$materialId',
  getParentRoute: () => AppMaterialsRouteRoute,
} as any)
const AppPurchasesIndexRoute = AppPurchasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPurchasesRouteRoute,
} as any)
const AppRateAnalysisIndexRoute = AppRateAnalysisIndexRouteImport.update({
  id: '/rate-analysis/',
  path: '/rate-analysis/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersIndexRoute = AppSalesOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesOrdersRouteRoute,
} as any)
const AppSalesOrdersOrderIdRoute = AppSalesOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AppSalesOrdersRouteRoute,
} as any)
const AppSupplierStockIndexRoute = AppSupplierStockIndexRouteImport.update({
  id: '/supplier-stock/',
  path: '/supplier-stock/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/companies': typeof AppCompaniesRouteRouteWithChildren
  '/deliveries': typeof AppDeliveriesRouteRouteWithChildren
  '/materials': typeof AppMaterialsRouteRouteWithChildren
  '/purchases': typeof AppPurchasesRouteRouteWithChildren
  '/sales-orders': typeof AppSalesOrdersRouteRouteWithChildren
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/materials/$materialId': typeof AppMaterialsMaterialIdRoute
  '/sales-orders/$orderId': typeof AppSalesOrdersOrderIdRoute
  '/companies/': typeof AppCompaniesIndexRoute
  '/company-report/': typeof AppCompanyReportIndexRoute
  '/deliveries/': typeof AppDeliveriesIndexRoute
  '/materials/': typeof AppMaterialsIndexRoute
  '/purchases/': typeof AppPurchasesIndexRoute
  '/rate-analysis/': typeof AppRateAnalysisIndexRoute
  '/sales-orders/': typeof AppSalesOrdersIndexRoute
  '/supplier-stock/': typeof AppSupplierStockIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/materials/$materialId': typeof AppMaterialsMaterialIdRoute
  '/sales-orders/$orderId': typeof AppSalesOrdersOrderIdRoute
  '/companies': typeof AppCompaniesIndexRoute
  '/company-report': typeof AppCompanyReportIndexRoute
  '/deliveries': typeof AppDeliveriesIndexRoute
  '/materials': typeof AppMaterialsIndexRoute
  '/purchases': typeof AppPurchasesIndexRoute
  '/rate-analysis': typeof AppRateAnalysisIndexRoute
  '/sales-orders': typeof AppSalesOrdersIndexRoute
  '/supplier-stock': typeof AppSupplierStockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/companies': typeof AppCompaniesRouteRouteWithChildren
  '/_app/deliveries': typeof AppDeliveriesRouteRouteWithChildren
  '/_app/materials': typeof AppMaterialsRouteRouteWithChildren
  '/_app/purchases': typeof AppPurchasesRouteRouteWithChildren
  '/_app/sales-orders': typeof AppSalesOrdersRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/_app/materials/$materialId': typeof AppMaterialsMaterialIdRoute
  '/_app/sales-orders/$orderId': typeof AppSalesOrdersOrderIdRoute
  '/_app/companies/': typeof AppCompaniesIndexRoute
  '/_app/company-report/': typeof AppCompanyReportIndexRoute
  '/_app/deliveries/': typeof AppDeliveriesIndexRoute
  '/_app/materials/': typeof AppMaterialsIndexRoute
  '/_app/purchases/': typeof AppPurchasesIndexRoute
  '/_app/rate-analysis/': typeof AppRateAnalysisIndexRoute
  '/_app/sales-orders/': typeof AppSalesOrdersIndexRoute
  '/_app/supplier-stock/': typeof AppSupplierStockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/companies'
    | '/deliveries'
    | '/materials'
    | '/purchases'
    | '/sales-orders'
    | '/companies/$companyId'
    | '/materials/$materialId'
    | '/sales-orders/$orderId'
    | '/companies/'
    | '/company-report/'
    | '/deliveries/'
    | '/materials/'
    | '/purchases/'
    | '/rate-analysis/'
    | '/sales-orders/'
    | '/supplier-stock/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/companies/$companyId'
    | '/materials/$materialId'
    | '/sales-orders/$orderId'
    | '/companies'
    | '/company-report'
    | '/deliveries'
    | '/materials'
    | '/purchases'
    | '/rate-analysis'
    | '/sales-orders'
    | '/supplier-stock'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/companies'
    | '/_app/deliveries'
    | '/_app/materials'
    | '/_app/purchases'
    | '/_app/sales-orders'
    | '/_app/'
    | '/_app/companies/$companyId'
    | '/_app/materials/$materialId'
    | '/_app/sales-orders/$orderId'
    | '/_app/companies/'
    | '/_app/company-report/'
    | '/_app/deliveries/'
    | '/_app/materials/'
    | '/_app/purchases/'
    | '/_app/rate-analysis/'
    | '/_app/sales-orders/'
    | '/_app/supplier-stock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliveries': {
      id: '/_app/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AppDeliveriesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materials': {
      id: '/_app/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AppMaterialsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-orders': {
      id: '/_app/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof AppSalesOrdersRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies/': {
      id: '/_app/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof AppCompaniesRouteRoute
    }
    '/_app/companies/$companyId': {
      id: '/_app/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AppCompaniesCompanyIdRouteImport
      parentRoute: typeof AppCompaniesRouteRoute
    }
    '/_app/company-report/': {
      id: '/_app/company-report/'
      path: '/company-report'
      fullPath: '/company-report/'
      preLoaderRoute: typeof AppCompanyReportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliveries/': {
      id: '/_app/deliveries/'
      path: '/'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof AppDeliveriesIndexRouteImport
      parentRoute: typeof AppDeliveriesRouteRoute
    }
    '/_app/materials/': {
      id: '/_app/materials/'
      path: '/'
      fullPath: '/materials/'
      preLoaderRoute: typeof AppMaterialsIndexRouteImport
      parentRoute: typeof AppMaterialsRouteRoute
    }
    '/_app/materials/$materialId': {
      id: '/_app/materials/$materialId'
      path: '/$materialId'
      fullPath: '/materials/$materialId'
      preLoaderRoute: typeof AppMaterialsMaterialIdRouteImport
      parentRoute: typeof AppMaterialsRouteRoute
    }
    '/_app/purchases/': {
      id: '/_app/purchases/'
      path: '/'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AppPurchasesIndexRouteImport
      parentRoute: typeof AppPurchasesRouteRoute
    }
    '/_app/rate-analysis/': {
      id: '/_app/rate-analysis/'
      path: '/rate-analysis'
      fullPath: '/rate-analysis/'
      preLoaderRoute: typeof AppRateAnalysisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-orders/': {
      id: '/_app/sales-orders/'
      path: '/'
      fullPath: '/sales-orders/'
      preLoaderRoute: typeof AppSalesOrdersIndexRouteImport
      parentRoute: typeof AppSalesOrdersRouteRoute
    }
    '/_app/sales-orders/$orderId': {
      id: '/_app/sales-orders/$orderId'
      path: '/$orderId'
      fullPath: '/sales-orders/$orderId'
      preLoaderRoute: typeof AppSalesOrdersOrderIdRouteImport
      parentRoute: typeof AppSalesOrdersRouteRoute
    }
    '/_app/supplier-stock/': {
      id: '/_app/supplier-stock/'
      path: '/supplier-stock'
      fullPath: '/supplier-stock/'
      preLoaderRoute: typeof AppSupplierStockIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCompaniesRouteRouteChildren {
  AppCompaniesCompanyIdRoute: typeof AppCompaniesCompanyIdRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
}

const AppCompaniesRouteRouteChildren: AppCompaniesRouteRouteChildren = {
  AppCompaniesCompanyIdRoute: AppCompaniesCompanyIdRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
}

const AppCompaniesRouteRouteWithChildren =
  AppCompaniesRouteRoute._addFileChildren(AppCompaniesRouteRouteChildren)

interface AppDeliveriesRouteRouteChildren {
  AppDeliveriesIndexRoute: typeof AppDeliveriesIndexRoute
}

const AppDeliveriesRouteRouteChildren: AppDeliveriesRouteRouteChildren = {
  AppDeliveriesIndexRoute: AppDeliveriesIndexRoute,
}

const AppDeliveriesRouteRouteWithChildren =
  AppDeliveriesRouteRoute._addFileChildren(AppDeliveriesRouteRouteChildren)

interface AppMaterialsRouteRouteChildren {
  AppMaterialsMaterialIdRoute: typeof AppMaterialsMaterialIdRoute
  AppMaterialsIndexRoute: typeof AppMaterialsIndexRoute
}

const AppMaterialsRouteRouteChildren: AppMaterialsRouteRouteChildren = {
  AppMaterialsMaterialIdRoute: AppMaterialsMaterialIdRoute,
  AppMaterialsIndexRoute: AppMaterialsIndexRoute,
}

const AppMaterialsRouteRouteWithChildren =
  AppMaterialsRouteRoute._addFileChildren(AppMaterialsRouteRouteChildren)

interface AppPurchasesRouteRouteChildren {
  AppPurchasesIndexRoute: typeof AppPurchasesIndexRoute
}

const AppPurchasesRouteRouteChildren: AppPurchasesRouteRouteChildren = {
  AppPurchasesIndexRoute: AppPurchasesIndexRoute,
}

const AppPurchasesRouteRouteWithChildren =
  AppPurchasesRouteRoute._addFileChildren(AppPurchasesRouteRouteChildren)

interface AppSalesOrdersRouteRouteChildren {
  AppSalesOrdersOrderIdRoute: typeof AppSalesOrdersOrderIdRoute
  AppSalesOrdersIndexRoute: typeof AppSalesOrdersIndexRoute
}

const AppSalesOrdersRouteRouteChildren: AppSalesOrdersRouteRouteChildren = {
  AppSalesOrdersOrderIdRoute: AppSalesOrdersOrderIdRoute,
  AppSalesOrdersIndexRoute: AppSalesOrdersIndexRoute,
}

const AppSalesOrdersRouteRouteWithChildren =
  AppSalesOrdersRouteRoute._addFileChildren(AppSalesOrdersRouteRouteChildren)

interface AppRouteChildren {
  AppCompaniesRouteRoute: typeof AppCompaniesRouteRouteWithChildren
  AppDeliveriesRouteRoute: typeof AppDeliveriesRouteRouteWithChildren
  AppMaterialsRouteRoute: typeof AppMaterialsRouteRouteWithChildren
  AppPurchasesRouteRoute: typeof AppPurchasesRouteRouteWithChildren
  AppSalesOrdersRouteRoute: typeof AppSalesOrdersRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCompanyReportIndexRoute: typeof AppCompanyReportIndexRoute
  AppRateAnalysisIndexRoute: typeof AppRateAnalysisIndexRoute
  AppSupplierStockIndexRoute: typeof AppSupplierStockIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompaniesRouteRoute: AppCompaniesRouteRouteWithChildren,
  AppDeliveriesRouteRoute: AppDeliveriesRouteRouteWithChildren,
  AppMaterialsRouteRoute: AppMaterialsRouteRouteWithChildren,
  AppPurchasesRouteRoute: AppPurchasesRouteRouteWithChildren,
  AppSalesOrdersRouteRoute: AppSalesOrdersRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCompanyReportIndexRoute: AppCompanyReportIndexRoute,
  AppRateAnalysisIndexRoute: AppRateAnalysisIndexRoute,
  AppSupplierStockIndexRoute: AppSupplierStockIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
